/** Spanish copy keyed by the canonical English translation in i18n.ts. */
export const ES_BY_ENGLISH: Record<string, string> = {
  "Elapsed": "Tiempo transcurrido",
  "Lock automatic preview switching": "Bloquear el cambio automático de vista previa",
  "Unlock automatic preview switching": "Desbloquear el cambio automático de vista previa",
  "Estimated remaining": "Tiempo restante estimado",
  "Calculating": "Calculando",
  "Finalizing": "Finalizando",
  "Advertisement": "Publicidad",
  "Ads will appear here after approval.": "Los anuncios aparecerán aquí después de la aprobación.",
  "Once images are loaded, all processing stays in this browser.": "Cuando cargues imágenes, todo el procesamiento se realizará en este navegador.",
  "A browser tool for transforming images and videos with palettes and pixel styles": "Una herramienta web para transformar imágenes y vídeos con paletas y estilos de píxel",
  "Go to the Palette Forge home page": "Ir a la página principal de Palette Forge",
  "A cup of coffee was added to the palette.": "Se añadió una taza de café a la paleta.",
  "A suspiciously good shade of green.": "Un verde sospechosamente bueno.",
  "RGB trio complete": "Trío RGB completado",
  "Apprentice Palette Maker": "Aprendiz de paletas",
  "Color Alchemist": "Alquimista del color",
  "Palette Forgemaster": "Maestro de la forja de paletas",
  "Completed {count} conversions in total.": "Has completado {count} conversiones en total.",
  "Dismiss notification": "Cerrar notificación",
  "Light": "Claro",
  "Dark": "Oscuro",
  "Switch to {mode} mode": "Cambiar al modo {mode}",
  "Select language": "Seleccionar idioma",
  "Add images": "Añadir imágenes",
  "Processing…": "Procesando…",
  "Convert": "Convertir",
  "Image list": "Lista de imágenes",
  "Load images": "Cargar imágenes",
  "PNG · JPEG · WebP / Multiple files supported": "PNG · JPEG · WebP / Se admiten varios archivos",
  "Or press Ctrl+V to paste an image": "O pulsa Ctrl+V para pegar una imagen",
  "Loaded {count} images from the clipboard.": "Se cargaron {count} imágenes desde el portapapeles.",
  "New images cannot be added while an image is being processed.": "No se pueden añadir imágenes mientras se procesa otra imagen.",
  "Images and videos stay in your browser and are never uploaded to a server.": "Las imágenes y los vídeos permanecen en tu navegador y nunca se suben a un servidor.",
  "Site information": "Información del sitio",
  "Guide": "Guía",
  "Privacy": "Privacidad",
  "Terms": "Términos",
  "Contact": "Contacto",
  "Done": "Listo",
  "Pending": "Pendiente",
  "No images loaded.": "No hay imágenes cargadas.",
  "Delete selected": "Eliminar selección",
  "Delete all": "Eliminar todo",
  "Remove all images from the list?": "¿Quieres eliminar todas las imágenes de la lista?",
  "Example": "Ejemplo",
  "Example · {name}": "Ejemplo · {name}",
  "Witch of Starlight": "Bruja de luz estelar",
  "City Monument": "Monumento urbano",
  "Knight of the Silver Blade": "Caballero de la espada de plata",
  "Golden Carbonara": "Carbonara dorada",
  "Coral Geometry": "Geometría coral",
  "Crate Fortress Squad": "Escuadrón de la fortaleza de cajas",
  "Cube Ranger": "Guardián cúbico",
  "Adventurer at the Sunlit Market": "Aventurera en el mercado soleado",
  "Loading and automatically converting an example image…": "Cargando y convirtiendo automáticamente una imagen de ejemplo…",
  "Preparing example image": "Preparando imagen de ejemplo",
  "Preparing an example image": "Preparando una imagen de ejemplo",
  "The image and its settings will load, then convert automatically.": "La imagen y sus ajustes se cargarán y se convertirán automáticamente.",
  "Loaded and converted the {name} example with its settings. The example stays in the list when you add your own image.": "Se cargó y convirtió el ejemplo {name} con sus ajustes. El ejemplo permanecerá en la lista cuando añadas tu propia imagen.",
  "The example image could not be loaded. Please add an image manually.": "No se pudo cargar la imagen de ejemplo. Añade una imagen manualmente.",
  "Preview": "Vista previa",
  "Original + adjusted preview": "Vista previa original y ajustada",
  "Wheel to zoom · Drag to pan · Click to sample color": "Rueda para ampliar · Arrastra para mover · Haz clic para tomar un color",
  "Converted result": "Resultado convertido",
  "{count} colors · Wheel to zoom · Drag to pan": "{count} colores · Rueda para ampliar · Arrastra para mover",
  "Not converted": "Sin convertir",
  "The result will appear after conversion.": "El resultado aparecerá después de la conversión.",
  "Load an image to refine its colors": "Carga una imagen para ajustar sus colores",
  "Files are never uploaded and are processed at full resolution in your browser.": "Los archivos nunca se suben y se procesan a resolución completa en tu navegador.",
  "Choose images": "Elegir imágenes",
  "Adjust colors": "Ajustar colores",
  "Reset": "Restablecer",
  "Each preview is recalculated from the original, so adjustments never accumulate.": "Cada vista previa se vuelve a calcular desde el original, por lo que los ajustes nunca se acumulan.",
  "Brightness": "Brillo",
  "Contrast": "Contraste",
  "Saturation": "Saturación",
  "Hue": "Tono",
  "Pixelation": "Pixelado",
  "Apply a block effect before color reduction": "Aplicar un efecto de bloques antes de reducir los colores",
  "Enable pixelation": "Activar pixelado",
  "Block size": "Tamaño de bloque",
  "Pixelation block size number": "Número de tamaño del bloque de pixelado",
  "Pixelation block size slider": "Control del tamaño del bloque de pixelado",
  "Alpha mode": "Modo alfa",
  "Pixelation alpha mode": "Modo alfa del pixelado",
  "Smooth alpha": "Alfa suave",
  "Binary alpha (opaque pixels)": "Alfa binario (píxeles opacos)",
  "Binary alpha makes a block fully opaque only when its average opacity is at least 50%.": "El alfa binario hace que un bloque sea totalmente opaco solo cuando su opacidad media es de al menos el 50 %.",
  "Final palette": "Paleta final",
  "Fixed {count}": "Fijos: {count}",
  "Reset all fixed colors and weights": "Restablecer todos los colores fijos y pesos",
  "Reset all fixed colors and weights.": "Se restablecieron todos los colores fijos y pesos.",
  "Presets": "Preajustes",
  "Palette presets": "Preajustes de paleta",
  "Close palette presets": "Cerrar los preajustes de paleta",
  "Choose a palette to apply its color count and fixed slots immediately.": "Elige una paleta para aplicar al instante su número de colores y sus ranuras fijas.",
  "{name} · {count} colors": "{name} · {count} colores",
  "Applied the {name} preset. Press Convert to update the result.": "Se aplicó el preajuste {name}. Pulsa Convertir para actualizar el resultado.",
  "Game Boy": "Game Boy",
  "Grayscale": "Escala de grises",
  "Warm earth": "Tierra cálida",
  "Ocean": "Océano",
  "Sunset": "Atardecer",
  "Prism pop": "Pop prismático",
  "Cyber neon": "Neón cibernético",
  "Retro arcade": "Arcade retro",
  "Final color count": "Número final de colores",
  "Max {max}": "Máx. {max}",
  "Choose color {index}": "Elegir color {index}",
  "Fixed": "Fijo",
  "Color fixed": "Color fijo",
  "Auto": "Auto",
  "Manual": "Manual",
  "Weight": "Peso",
  "Fix the color and keep its weight automatic": "Fijar el color y mantener su peso automático",
  "Fix both the color and its current weight": "Fijar tanto el color como su peso actual",
  "Return both color and weight to automatic": "Volver a poner el color y el peso en automático",
  "Convert first to generate an automatic color, or fix the color manually.": "Convierte primero para generar un color automático o fija el color manualmente.",
  "Fix the color before adjusting its weight.": "Fija el color antes de ajustar su peso.",
  "Clear fixed color and restore automatic weight": "Quitar el color fijo y restaurar el peso automático",
  "Delete palette color {index}": "Eliminar el color {index} de la paleta",
  "A palette must contain at least one color.": "Una paleta debe contener al menos un color.",
  "Deleted color {index} from the palette.": "Se eliminó el color {index} de la paleta.",
  "direct number input": "entrada numérica directa",
  "{name} must be an integer from {min} to {max}. The previous value was restored.": "{name} debe ser un entero entre {min} y {max}. Se restauró el valor anterior.",
  "Cosmic candy": "Caramelo cósmico",
  "Amber ink": "Tinta ámbar",
  "Automatic palette tendency": "Tendencia de la paleta automática",
  "Automatic palette tendency number": "Número de tendencia de la paleta automática",
  "Automatic palette tendency must be an integer from -50 to 50. The previous value was restored.": "La tendencia de la paleta automática debe ser un entero entre -50 y 50. Se restauró el valor anterior.",
  "Dominant colors": "Colores dominantes",
  "Original balance": "Equilibrio original",
  "Color diversity": "Diversidad de colores",
  "Surface cleanup": "Limpieza de superficies",
  "Surface cleanup number": "Número de limpieza de superficies",
  "Surface cleanup must be an integer from 0 to 100. The previous value was restored.": "La limpieza de superficies debe ser un entero entre 0 y 100. Se restauró el valor anterior.",
  "Preserve detail": "Conservar detalle",
  "Balanced": "Equilibrado",
  "Clean surfaces": "Superficies limpias",
  "Save & export": "Guardar y exportar",
  "Save settings": "Guardar ajustes",
  "Load settings": "Cargar ajustes",
  "Format": "Formato",
  "Quality": "Calidad",
  "File name": "Nombre del archivo",
  "Background": "Fondo",
  "Preserve alpha": "Conservar alfa",
  "Pixelated output resolution": "Resolución de salida pixelada",
  "Keep original resolution": "Mantener resolución original",
  "Pixel optimized": "Optimizada para píxeles",
  "JPEG does not support transparency, so the image will be composited onto the selected background color.": "JPEG no admite transparencia, por lo que la imagen se compondrá sobre el color de fondo seleccionado.",
  "Export current": "Exportar actual",
  "Export all": "Exportar todo",
  "Choose settings to save": "Elegir ajustes para guardar",
  "Close save settings dialog": "Cerrar el diálogo de guardado de ajustes",
  "Choose what to include in the file. Select at least one item.": "Elige qué incluir en el archivo. Selecciona al menos un elemento.",
  "Save ADJUST color settings": "Guardar los ajustes de color de ADJUST",
  "ADJUST · Color adjustments": "ADJUST · Ajustes de color",
  "Brightness, contrast, saturation, hue, and pixelation": "Brillo, contraste, saturación, tono y pixelado",
  "Save PALETTE settings": "Guardar los ajustes de PALETTE",
  "PALETTE · Final palette": "PALETTE · Paleta final",
  "Color count, automatic palette tendency, surface cleanup, fixed colors, and weights": "Número de colores, tendencia automática, limpieza de superficies, colores fijos y pesos",
  "Export format, file name, and transparency settings are always saved. Settings omitted from the file keep their current values when loaded.": "El formato de exportación, el nombre del archivo y la transparencia siempre se guardan. Los ajustes omitidos conservan sus valores actuales al cargar el archivo.",
  "Cancel": "Cancelar",
  "Save selected": "Guardar selección",
  "Color picker": "Selector de color",
  "Slot {index} color": "Color de la ranura {index}",
  "Saturation and brightness area": "Área de saturación y brillo",
  "Image eyedropper": "Cuentagotas de imagen",
  "Screen eyedropper": "Cuentagotas de pantalla",
  "The screen eyedropper is available only in supported browsers. Fully transparent pixels cannot be selected.": "El cuentagotas de pantalla solo está disponible en navegadores compatibles. No se pueden seleccionar píxeles totalmente transparentes.",
  "Fix color": "Fijar color",
  "Converted image": "Imagen convertida",
  "Adjusted original image": "Imagen original ajustada",
  "Original image": "Imagen original",
  "Switch between original and adjusted previews": "Cambiar entre las vistas original y ajustada",
  "Original": "Original",
  "Adjusted": "Ajustada",
  "Preparing preview…": "Preparando vista previa…",
  "Applying color adjustments and pixelation.": "Aplicando ajustes de color y pixelado.",
  "Could not prepare the preview.": "No se pudo preparar la vista previa.",
  "Change the settings or load the image again.": "Cambia los ajustes o vuelve a cargar la imagen.",
  "Fit view": "Ajustar a la vista",
  "View at 100%": "Ver al 100 %",
  "{name}: Only PNG, JPEG, and WebP are supported.": "{name}: solo se admiten PNG, JPEG y WebP.",
  "{name}: The file is damaged or could not be decoded.": "{name}: el archivo está dañado o no se pudo decodificar.",
  "Loaded {count} images in their original order.": "Se cargaron {count} imágenes en su orden original.",
  "The final color count must be an integer from 1 to {max}.": "El número final de colores debe ser un entero entre 1 y {max}.",
  "Some fixed colors fall outside the new range. Delete those slots?": "Algunos colores fijos quedan fuera del nuevo intervalo. ¿Quieres eliminar esas ranuras?",
  "Changed the palette to {count} slots.": "La paleta se cambió a {count} ranuras.",
  "Enter HEX as #RRGGBB and each RGB value from 0 to 255, with matching values.": "Introduce HEX como #RRGGBB y cada valor RGB entre 0 y 255, asegurándote de que coincidan.",
  "A color cannot be sampled from a fully transparent pixel.": "No se puede tomar un color de un píxel totalmente transparente.",
  "Fixed {hex} and applied it to the palette.": "Se fijó {hex} y se aplicó a la paleta.",
  "This browser does not support the screen eyedropper. Use the image eyedropper instead.": "Este navegador no admite el cuentagotas de pantalla. Usa el cuentagotas de imagen.",
  "Screen eyedropper canceled.": "Se canceló el cuentagotas de pantalla.",
  "Converting at full resolution…": "Convirtiendo a resolución completa…",
  "Conversion complete.": "Conversión completada.",
  "Image conversion failed.": "La conversión de la imagen falló.",
  "Saved the {sections} settings file.": "Se guardó el archivo de ajustes de {sections}.",
  "Could not save settings.": "No se pudieron guardar los ajustes.",
  "Applied {sections} settings to the current image.": "Se aplicaron los ajustes de {sections} a la imagen actual.",
  "Could not load the settings file.": "No se pudo cargar el archivo de ajustes.",
  "Exported the current image.": "Se exportó la imagen actual.",
  "Image export failed.": "La exportación de la imagen falló.",
  "Some images could not be exported: {names}": "No se pudieron exportar algunas imágenes: {names}",
  "Exported {count} images.": "Se exportaron {count} imágenes.",
  "Weight must be a number from 0.1 to 5. The previous value was restored.": "El peso debe ser un número entre 0,1 y 5. Se restauró el valor anterior.",
  "Pixelation block size must be an integer from 2 to 64. The previous value was restored.": "El tamaño del bloque de pixelado debe ser un entero entre 2 y 64. Se restauró el valor anterior.",
  "Click the desired pixel in the original or converted image.": "Haz clic en el píxel deseado de la imagen original o convertida.",
  "Convert the image first.": "Convierte primero la imagen.",
  "Could not start image conversion.": "No se pudo iniciar la conversión de la imagen.",
  "This browser cannot export the selected format.": "Este navegador no puede exportar el formato seleccionado.",
  "The settings file format is invalid.": "El formato del archivo de ajustes no es válido.",
  "The number of palette slots does not match the final color count.": "El número de ranuras de la paleta no coincide con el número final de colores.",
  "Hue must be from -180 to 180.": "El tono debe estar entre -180 y 180.",
  "The pixelation enabled value is invalid.": "El valor de activación del pixelado no es válido.",
  "Pixel size must be an integer from 2 to 64.": "El tamaño de píxel debe ser un entero entre 2 y 64.",
  "The pixelation alpha mode is invalid.": "El modo alfa del pixelado no es válido.",
  "The automatic palette tendency must be an integer from 0 to 100.": "La tendencia de la paleta automática debe ser un entero entre 0 y 100.",
  "Surface cleanup must be an integer from 0 to 100.": "La limpieza de superficies debe ser un entero entre 0 y 100.",
  "The weight mode for slot {index} is invalid.": "El modo de peso de la ranura {index} no es válido.",
  "The output format is not supported.": "El formato de salida no es compatible.",
  "The output file name is empty.": "El nombre del archivo de salida está vacío.",
  "Quality must be from 0.1 to 1.": "La calidad debe estar entre 0,1 y 1.",
  "The background color is invalid.": "El color de fondo no es válido.",
  "The transparency setting is invalid.": "El ajuste de transparencia no es válido.",
  "The output resolution setting is invalid.": "El ajuste de resolución de salida no es válido.",
  "Select at least one settings section to save.": "Selecciona al menos una sección de ajustes para guardar.",
  "The saved section metadata is invalid.": "Los metadatos de las secciones guardadas no son válidos.",
  "The JSON is invalid.": "El JSON no es válido.",
  "The ADJUST settings are missing.": "Faltan los ajustes de ADJUST.",
  "The PALETTE settings are missing.": "Faltan los ajustes de PALETTE.",
  "Video": "Vídeo",
  "Video palette conversion": "Conversión de paleta de vídeo",
  "Close video converter": "Cerrar el conversor de vídeo",
  "Videos are processed in this browser and never uploaded to a server.": "Los vídeos se procesan en este navegador y nunca se suben a un servidor.",
  "Only MP4 and WebM videos are supported.": "Solo se admiten vídeos MP4 y WebM.",
  "This browser does not support video conversion. Use the latest Chrome or Edge.": "Este navegador no admite la conversión de vídeo. Usa la versión más reciente de Chrome o Edge.",
  "The video file cannot be read.": "No se puede leer el archivo de vídeo.",
  "The file has no video track.": "El archivo no contiene una pista de vídeo.",
  "This browser cannot decode the video codec.": "Este navegador no puede decodificar el códec de vídeo.",
  "Could not load the video.": "No se pudo cargar el vídeo.",
  "Could not determine the video's dimensions or duration.": "No se pudieron determinar las dimensiones o la duración del vídeo.",
  "The video is ready. Review the settings and start conversion.": "El vídeo está listo. Revisa los ajustes e inicia la conversión.",
  "Analyzing a common palette across the video.": "Analizando una paleta común para todo el vídeo.",
  "Converting with a palette generated for each frame.": "Convirtiendo con una paleta generada para cada fotograma.",
  "Converting video frames.": "Convirtiendo fotogramas de vídeo.",
  "Finalizing the video file.": "Finalizando el archivo de vídeo.",
  "Video conversion is complete.": "La conversión del vídeo ha terminado.",
  "Video conversion is complete. The original audio was preserved without re-encoding.": "La conversión del vídeo ha terminado. El audio original se conservó sin volver a codificarlo.",
  "Video conversion was canceled.": "Se canceló la conversión del vídeo.",
  "Video conversion failed.": "La conversión del vídeo falló.",
  "Could not create the video analysis canvas.": "No se pudo crear el lienzo para analizar el vídeo.",
  "Could not create the video conversion canvas.": "No se pudo crear el lienzo para convertir el vídeo.",
  "No frames were available for analysis.": "No había fotogramas disponibles para el análisis.",
  "This browser cannot encode the selected video format.": "Este navegador no puede codificar el formato de vídeo seleccionado.",
  "The original audio cannot be preserved for this file.": "No se puede conservar el audio original de este archivo.",
  "Could not create the converted video file.": "No se pudo crear el archivo de vídeo convertido.",
  "Inspecting video…": "Comprobando el vídeo…",
  "Choose another video": "Elegir otro vídeo",
  "Choose an MP4 or WebM video": "Elegir un vídeo MP4 o WebM",
  "One video is processed at a time.": "Se procesa un vídeo cada vez.",
  "No audio": "Sin audio",
  "Original video": "Vídeo original",
  "Choose a video.": "Elige un vídeo.",
  "The result will appear when conversion finishes.": "El resultado aparecerá cuando termine la conversión.",
  "Latest converted frame preview": "Vista previa del último fotograma convertido",
  "Converted frames will appear after palette analysis.": "Los fotogramas convertidos aparecerán después del análisis de la paleta.",
  "Preparing the first converted frame.": "Preparando el primer fotograma convertido.",
  "Analyzing palette": "Analizando paleta",
  "Converting frames": "Convirtiendo fotogramas",
  "Finalizing video": "Finalizando vídeo",
  "Latest completed frame": "Último fotograma completado",
  "Adjustment preview": "Vista previa de ajustes",
  "Current-frame adjustment preview": "Vista previa de ajustes del fotograma actual",
  "Preparing an adjustment preview of the current frame.": "Preparando una vista previa de ajustes del fotograma actual.",
  "Could not display the adjustment preview.": "No se pudo mostrar la vista previa de ajustes.",
  "Color adjustment, single-color tint, and pixelation preview": "Vista previa de ajuste de color, tinte de un solo color y pixelado",
  "Final palette not applied": "Paleta final no aplicada",
  "Analyzing the video-wide color reference.": "Analizando la referencia de color de todo el vídeo.",
  "Could not analyze the video-wide color reference.": "No se pudo analizar la referencia de color de todo el vídeo.",
  "Video-wide color reference": "Referencia de color de todo el vídeo",
  "Keeps every frame's brightness and color intensity while unifying the video around one representative hue, then shifts it with the Hue control.": "Conserva el brillo y la intensidad de color de cada fotograma, unifica el vídeo con un tono representativo y permite desplazarlo con el control de tono.",
  "Palette generation": "Generación de paleta",
  "Common palette for the entire video": "Paleta común para todo el vídeo",
  "Analyzes the entire video and uses one palette. Recommended by default to reduce color flicker.": "Analiza todo el vídeo y utiliza una sola paleta. Se recomienda como opción predeterminada para reducir el parpadeo de color.",
  "Automatic palette per frame": "Paleta automática por fotograma",
  "Blends each frame palette smoothly with recent frames while applying scene changes immediately.": "Combina suavemente la paleta de cada fotograma con las recientes y aplica de inmediato los cambios de escena.",
  "Video palette": "Paleta de vídeo",
  "Video palette presets": "Preajustes de paleta de vídeo",
  "Applied the {name} preset to the video palette.": "Se aplicó el preajuste {name} a la paleta de vídeo.",
  "Color count": "Número de colores",
  "Palette color {index}": "Color de paleta {index}",
  "Palette weight {index}": "Peso de paleta {index}",
  "Preparing video conversion": "Preparando la conversión del vídeo",
  "Total elapsed": "Tiempo total transcurrido",
  "Stage elapsed": "Tiempo transcurrido en la etapa",
  "Calculating remaining time": "Calculando el tiempo restante",
  "About {time} remaining": "Quedan unos {time}",
  "Finalizing file": "Finalizando archivo",
  "Processing in your browser. Do not close this tab.": "Procesando en tu navegador. No cierres esta pestaña.",
  "Applied common palette": "Paleta común aplicada",
  "Frequently used frame colors": "Colores más usados en los fotogramas",
  "Preserve original audio packets": "Conservar los paquetes de audio originales",
  "Cancel conversion": "Cancelar conversión",
  "Close": "Cerrar",
  "Convert again": "Convertir de nuevo",
  "Convert video": "Convertir vídeo",
  "Save converted video": "Guardar vídeo convertido",
  "Reset color adjustments and pixelation.": "Se restablecieron los ajustes de color y el pixelado.",
  "Reset fixed video palette colors and weights.": "Se restablecieron los colores fijos y los pesos de la paleta de vídeo.",
  "Fixed colors and weights below are ignored in automatic palette-per-frame mode.": "Los colores fijos y los pesos de abajo se ignoran en el modo de paleta automática por fotograma.",
  "Open image list help": "Abrir la ayuda de la lista de imágenes",
  "Load images for conversion and choose which image to edit.": "Carga imágenes para convertirlas y elige cuál quieres editar.",
  "You can select multiple PNG, JPEG, or WebP files, drag files or web images, or paste with Ctrl+V.": "Puedes seleccionar varios archivos PNG, JPEG o WebP, arrastrar archivos o imágenes web, o pegar con Ctrl+V.",
  "Selecting an image in the list switches the preview and controls to that image's individual settings.": "Al seleccionar una imagen de la lista, la vista previa y los controles cambian a sus ajustes individuales.",
  "Organize the list": "Organizar la lista",
  "Delete selected removes only the current item; Delete all clears the list. Your original files are never deleted.": "Eliminar selección quita solo el elemento actual; Eliminar todo vacía la lista. Tus archivos originales nunca se eliminan.",
  "Drop to add images": "Suelta para añadir imágenes",
  "Drag files or web images here": "Arrastra aquí archivos o imágenes web",
  "No image file or image address was found in the dragged item.": "No se encontró ningún archivo ni dirección de imagen en el elemento arrastrado.",
  "The website does not allow this image to be imported. Save it first, then drag the file here.": "El sitio web no permite importar esta imagen. Guárdala primero y después arrastra el archivo aquí.",
  "Open preview help": "Abrir la ayuda de vista previa",
  "Using the preview": "Uso de la vista previa",
  "Check the original and adjusted view above, then compare the palette conversion result below.": "Comprueba arriba las vistas original y ajustada y compara abajo el resultado de la conversión de paleta.",
  "Use the mouse wheel to zoom and drag to pan.": "Usa la rueda del ratón para ampliar y arrastra para desplazarte.",
  "Click the image to sample that pixel into the palette.": "Haz clic en la imagen para añadir el color de ese píxel a la paleta.",
  "Use the lower-right controls to switch or lock the original and adjusted view, and to fit the image.": "Usa los controles inferiores derechos para cambiar o bloquear la vista original y ajustada, y para encajar la imagen.",
  "Open color adjustment help": "Abrir la ayuda de ajustes de color",
  "Using color adjustments": "Uso de los ajustes de color",
  "Apply brightness, contrast, saturation, hue, and pixelation before generating the palette.": "Aplica brillo, contraste, saturación, tono y pixelado antes de generar la paleta.",
  "Every change is recalculated from the original, so repeated adjustments never accumulate.": "Cada cambio se vuelve a calcular desde el original, por lo que los ajustes repetidos nunca se acumulan.",
  "Larger pixel blocks create a coarser pixel style.": "Los bloques de píxeles más grandes crean un estilo de píxel más grueso.",
  "For transparent PNGs, choose smooth alpha or binary alpha.": "Para PNG transparentes, elige alfa suave o alfa binario.",
  "Open final palette help": "Abrir la ayuda de paleta final",
  "Using the final palette": "Uso de la paleta final",
  "Choose the final color count and palette tendency, then fix any required colors to exact values.": "Elige el número final de colores y la tendencia de la paleta; después fija con valores exactos los colores necesarios.",
  "Auto calculates the color and weight; Color fixed preserves only the color; Fixed preserves both.": "Auto calcula el color y el peso; Color fijo conserva solo el color; Fijo conserva ambos.",
  "A higher weight lets that color cover a wider matching range.": "Un peso mayor permite que ese color abarque un intervalo de coincidencia más amplio.",
  "Use palette tendency and surface cleanup to balance source fidelity and visual style.": "Usa la tendencia de la paleta y la limpieza de superficies para equilibrar la fidelidad al original y el estilo visual.",
  "Open save and export help": "Abrir la ayuda de guardado y exportación",
  "Saving and exporting": "Guardado y exportación",
  "Save your working settings as JSON and export results as PNG, JPEG, or WebP images.": "Guarda los ajustes de trabajo como JSON y exporta los resultados como imágenes PNG, JPEG o WebP.",
  "PNG and WebP can preserve transparency; JPEG is composited onto the selected background.": "PNG y WebP pueden conservar la transparencia; JPEG se compone sobre el fondo seleccionado.",
  "When pixelation is enabled, choose the original resolution or a block-optimized resolution.": "Cuando el pixelado esté activo, elige la resolución original o una resolución optimizada para los bloques.",
  "With multiple images, export only the current image or export every image separately.": "Con varias imágenes, exporta solo la actual o exporta cada imagen por separado.",
  "Open palette generation help": "Abrir la ayuda de generación de paleta",
  "Video palette generation": "Generación de paleta de vídeo",
  "Choose one palette for the whole video or recalculate the palette for every frame.": "Elige una paleta para todo el vídeo o vuelve a calcularla para cada fotograma.",
  "The common palette analyzes the whole video and reduces flicker, so it is recommended by default.": "La paleta común analiza todo el vídeo y reduce el parpadeo, por lo que se recomienda como opción predeterminada.",
  "Per-frame palettes reflect each scene better, but visible color shifts may appear in some videos.": "Las paletas por fotograma reflejan mejor cada escena, pero en algunos vídeos pueden aparecer cambios de color visibles.",
  "Open video adjustment help": "Abrir la ayuda de ajustes de vídeo",
  "Using video adjustments": "Uso de los ajustes de vídeo",
  "Apply the same brightness, contrast, saturation, hue, and pixelation settings to every frame.": "Aplica los mismos ajustes de brillo, contraste, saturación, tono y pixelado a cada fotograma.",
  "Color adjustments and pixelation are applied before palette generation and color mapping.": "Los ajustes de color y el pixelado se aplican antes de generar la paleta y asignar los colores.",
  "A larger block size creates a coarser pixel look in the video.": "Un tamaño de bloque mayor crea un aspecto de píxel más grueso en el vídeo.",
  "Open video palette help": "Abrir la ayuda de paleta de vídeo",
  "Using the video palette": "Uso de la paleta de vídeo",
  "Set the final video color count and automatic palette tendency, and fix colors for common-palette mode.": "Define el número final de colores y la tendencia automática, y fija colores para el modo de paleta común.",
  "In common-palette mode, presets, fixed colors, and weights apply to every frame.": "En el modo de paleta común, los preajustes, colores fijos y pesos se aplican a cada fotograma.",
  "Higher surface cleanup reduces small color speckles and produces cleaner broad areas.": "Una limpieza de superficies mayor reduce las pequeñas motas de color y crea áreas amplias más limpias.",
  "Check the original and adjusted view above first, then compare the converted result below.": "Primero comprueba arriba las vistas original y ajustada y después compara abajo el resultado convertido.",
  "Zoom and pan": "Ampliar y desplazar",
  "Use the eyedropper": "Usar el cuentagotas",
  "Only after opening the color swatch on a palette slot and choosing Image eyedropper can you click a pixel in this preview to sample its color.": "Solo después de abrir la muestra de color de una ranura y elegir Cuentagotas de imagen podrás hacer clic en un píxel de esta vista previa para tomar su color.",
  "Switch the view": "Cambiar la vista",
  "Change the image brightness, color feel, and pixel shape before reducing its colors. Every change is recalculated from the original.": "Cambia el brillo, el aspecto cromático y la forma de los píxeles antes de reducir los colores. Cada cambio se recalcula desde el original.",
  "Brightness and contrast": "Brillo y contraste",
  "Brightness makes the whole image lighter or darker. Contrast changes the difference between light and dark areas.": "El brillo aclara u oscurece toda la imagen. El contraste cambia la diferencia entre las zonas claras y oscuras.",
  "Saturation and hue": "Saturación y tono",
  "Saturation changes color intensity. Hue shifts all colors toward a different color family.": "La saturación cambia la intensidad del color. El tono desplaza todos los colores hacia otra familia cromática.",
  "Groups the image into square blocks. Larger blocks create coarser pixels.": "Agrupa la imagen en bloques cuadrados. Los bloques mayores crean píxeles más gruesos.",
  "Binary alpha": "Alfa binario",
  "Keeps partial transparency so edges and shadows remain smooth.": "Conserva la transparencia parcial para que los bordes y las sombras sigan siendo suaves.",
  "Makes each block fully transparent or fully opaque for crisp pixel edges.": "Hace que cada bloque sea totalmente transparente u opaco para crear bordes de píxel nítidos.",
  "Choose the final color count and the colors in each palette slot. Click the color swatch on the left to set a color directly.": "Elige la cantidad final de colores y los colores de cada ranura. Haz clic en la muestra de la izquierda para definir un color directamente.",
  "Set the color count": "Definir la cantidad de colores",
  "Changing Final color count changes the number of palette slots below to match.": "Al cambiar la cantidad final de colores, el número de ranuras de abajo se ajusta para coincidir.",
  "Set a color directly": "Definir un color directamente",
  "Click the color swatch on the left of a slot to open the color picker. Enter HEX or RGB, or choose Image eyedropper and click the desired color in the preview.": "Haz clic en la muestra de color situada a la izquierda de una ranura para abrir el selector. Introduce HEX o RGB, o elige Cuentagotas de imagen y pulsa el color deseado en la vista previa.",
  "Auto, Color fixed, and Fixed": "Auto, Color fijo y Fijo",
  "Auto calculates color and weight. Color fixed preserves only the selected color. Fixed preserves both color and weight.": "Auto calcula el color y el peso. Color fijo conserva solo el color seleccionado. Fijo conserva tanto el color como el peso.",
  "Raise the value to map more similar pixels to that palette color.": "Aumenta el valor para asignar más píxeles similares a ese color de la paleta.",
  "Adjust automatic generation": "Ajustar la generación automática",
  "Automatic palette tendency changes how automatic colors are chosen; Surface cleanup changes how clean and broad the converted color areas appear.": "La tendencia de paleta automática cambia cómo se eligen los colores; la limpieza de superficies ajusta lo limpias y amplias que se ven las áreas convertidas.",
  "The left favors colors used most in the image; the right selects a wider variety of distinct colors.": "La izquierda favorece los colores más usados en la imagen; la derecha selecciona una variedad mayor de colores distintos.",
  "Lower values preserve small color details. Higher values remove speckles and clean up broad areas.": "Los valores bajos conservan pequeños detalles de color. Los altos eliminan motas y limpian áreas amplias.",
  "Save the current work as a settings file for later, or download the finished image.": "Guarda el trabajo actual como archivo de ajustes para continuarlo más tarde o descarga la imagen terminada.",
  "Saves color adjustments and palette values in a JSON file. The original image is not included.": "Guarda los ajustes de color y los valores de la paleta en un archivo JSON. La imagen original no se incluye.",
  "Transparency": "Transparencia",
  "PNG and WebP can preserve transparency. JPEG fills transparent areas with the selected background color.": "PNG y WebP pueden conservar la transparencia. JPEG rellena las zonas transparentes con el color de fondo seleccionado.",
  "Pixelated resolution": "Resolución pixelada",
  "Keep the original dimensions or save a smaller image where each block becomes one output pixel.": "Conserva las dimensiones originales o guarda una imagen más pequeña en la que cada bloque sea un píxel de salida.",
  "Exporting multiple images": "Exportación de varias imágenes",
  "Save only the current image or save every image in the list separately.": "Guarda solo la imagen actual o cada imagen de la lista por separado.",
  "Choose whether the video keeps one color standard or changes its palette with each scene.": "Elige si el vídeo mantiene un único criterio de color o cambia de paleta con cada escena.",
  "Analyzes the whole video first and uses the same color list throughout. Recommended by default because it reduces flicker.": "Analiza primero todo el vídeo y utiliza la misma lista de colores hasta el final. Se recomienda porque reduce el parpadeo.",
  "Chooses colors again for each scene. Scene colors are represented better, but visible color shifts may appear in some videos.": "Vuelve a elegir los colores para cada escena. Representa mejor sus colores, aunque algunos vídeos pueden mostrar cambios visibles.",
  "Applies the same color adjustments and pixel shape to every frame.": "Aplica los mismos ajustes de color y la misma forma de píxel a cada fotograma.",
  "Adjusts overall video brightness and the difference between light and dark areas.": "Ajusta el brillo general del vídeo y la diferencia entre las zonas claras y oscuras.",
  "Adjusts color intensity and the overall color family.": "Ajusta la intensidad y la familia cromática general.",
  "Groups the video into square blocks before conversion. Larger blocks create coarser pixels.": "Agrupa el vídeo en bloques cuadrados antes de convertirlo. Los bloques mayores crean píxeles más gruesos.",
  "Sets the color count and selection rules actually used in the converted video.": "Define el número de colores y las reglas de selección que se usarán en el vídeo convertido.",
  "With a common palette": "Con una paleta común",
  "Presets, fixed colors, and weights apply equally to every frame.": "Los preajustes, colores fijos y pesos se aplican por igual a todos los fotogramas.",
  "With per-frame palettes": "Con paletas por fotograma",
  "Each frame chooses colors again automatically, so the fixed colors and weights below are ignored.": "Cada fotograma vuelve a elegir los colores automáticamente, por lo que se ignoran los colores fijos y pesos de abajo.",
  "Higher values reduce small color speckles and produce cleaner broad color areas.": "Los valores altos reducen las pequeñas motas y producen áreas amplias de color más limpias.",
  "Estimated workload": "Carga estimada",
  "Smooth": "Fluida",
  "Caution": "Precaución",
  "Risk": "Riesgo",
  "High resolution": "Alta resolución",
  "Long duration": "Duración larga",
  "Large file": "Archivo grande",
  "Limited device memory": "Memoria limitada del dispositivo",
  "This video is expected to process relatively smoothly based on its current information.": "Según la información disponible, se espera que este vídeo se procese con relativa fluidez.",
  "Processing may take longer or use substantial memory. Closing other tabs is recommended.": "El procesamiento puede tardar más o usar mucha memoria. Se recomienda cerrar otras pestañas.",
  "The browser tab may stop responding. Shorten the video or lower its resolution before converting.": "La pestaña del navegador podría dejar de responder. Acorta el vídeo o reduce su resolución antes de convertirlo.",
  "This estimate uses information exposed by the browser and may differ from the memory actually available.": "Esta estimación usa la información que proporciona el navegador y puede diferir de la memoria realmente disponible.",
  "This video is expected to place a very high load on browser memory and the tab may stop. Convert it anyway?": "Se espera que este vídeo consuma mucha memoria del navegador y la pestaña podría detenerse. ¿Quieres convertirlo de todos modos?",
  "Drop anywhere on the site to add images": "Suelta imágenes en cualquier parte del sitio para añadirlas",
  "Add images and choose one to edit.": "Añade imágenes y elige una para editar.",
  "Choose PNG, JPEG, or WebP files, drag them anywhere on the site, or paste with Ctrl+V.": "Elige archivos PNG, JPEG o WebP, arrástralos a cualquier parte del sitio o pégalos con Ctrl+V.",
  "Select an image to open it with its settings.": "Selecciona una imagen para abrirla con sus ajustes.",
  "Deleting here only removes it from the list. The original file stays intact.": "Borrarla aquí solo la quita de la lista. El archivo original no cambia.",
  "The original and adjusted view is above; the converted result is below.": "Arriba están el original y el ajuste; abajo, el resultado convertido.",
  "Use the wheel to zoom and drag to pan.": "Usa la rueda para ampliar y arrastra para desplazarte.",
  "After opening a palette slot's left color swatch and choosing Image eyedropper, click the pixel you want in the preview.": "Tras abrir la muestra izquierda de una ranura y elegir Cuentagotas de imagen, pulsa el píxel deseado en la vista previa.",
  "Use the lower-right controls for Original/Adjusted, lock, and fit.": "Usa los controles inferiores derechos para Original/Ajustado, bloqueo y ajuste a pantalla.",
  "Adjust brightness, color, and pixelation before palette conversion.": "Ajusta el brillo, el color y el pixelado antes de convertir la paleta.",
  "Adjust overall brightness and contrast.": "Ajusta el brillo general y el contraste.",
  "Change color intensity and the overall color family.": "Cambia la intensidad y la familia cromática general.",
  "Larger blocks create coarser pixels.": "Los bloques mayores crean píxeles más gruesos.",
  "Keeps partial transparency for smooth edges.": "Conserva la transparencia parcial para suavizar los bordes.",
  "Uses only fully transparent or opaque pixels for crisp edges.": "Usa solo píxeles totalmente transparentes u opacos para crear bordes nítidos.",
  "Choose the color count and the colors used in the result.": "Elige la cantidad de colores y los que se usarán en el resultado.",
  "The palette gets one slot for each final color.": "La paleta crea una ranura por cada color final.",
  "Click a slot's left swatch to enter HEX or RGB, or use the Image eyedropper.": "Pulsa la muestra izquierda de una ranura para introducir HEX o RGB, o usa el Cuentagotas de imagen.",
  "Auto calculates everything; Color fixed keeps the color; Fixed keeps both color and weight.": "Auto calcula todo; Color fijo conserva el color; Fijo conserva el color y el peso.",
  "Higher values make that color appear more often.": "Los valores más altos hacen que ese color aparezca más.",
  "Palette tendency changes color selection; Surface cleanup changes how clean the result looks.": "La tendencia cambia la selección de colores; la limpieza de superficies ajusta la claridad del resultado.",
  "Save settings or download converted images.": "Guarda los ajustes o descarga las imágenes convertidas.",
  "Save adjustment and palette settings as JSON.": "Guarda los ajustes de corrección y paleta como JSON.",
  "PNG and WebP keep transparency; JPEG fills it with the background color.": "PNG y WebP conservan la transparencia; JPEG la rellena con el color de fondo.",
  "Save at the original size or a smaller size matched to pixel blocks.": "Guarda al tamaño original o a uno menor ajustado a los bloques de píxeles.",
  "Save the current image or every image in the list.": "Guarda la imagen actual o todas las de la lista.",
  "Choose one palette for the video or a new palette for each frame.": "Elige una paleta para todo el vídeo o una nueva para cada fotograma.",
  "Uses one palette throughout to reduce color flicker.": "Usa una sola paleta para reducir el parpadeo de color.",
  "Chooses colors for each frame to follow scene changes, but colors may shift.": "Elige colores por fotograma para seguir los cambios de escena, aunque pueden variar.",
  "Apply the same adjustments and pixelation to every frame.": "Aplica los mismos ajustes y pixelado a cada fotograma.",
  "Choose the video's color count and selection rules.": "Elige la cantidad de colores y las reglas de selección del vídeo.",
  "Apply presets, fixed colors, and weights to every frame.": "Aplica preajustes, colores fijos y pesos a cada fotograma.",
  "Generates colors automatically each time and ignores the fixed colors and weights below.": "Genera los colores automáticamente e ignora los colores fijos y pesos de abajo.",
  "Higher values reduce small color speckles and clean up broad areas.": "Los valores altos reducen pequeñas motas y limpian las áreas amplias.",
  "Load multiple images and choose which one to edit.": "Carga varias imágenes y elige cuál quieres editar.",
  "Choose PNG, JPEG, or WebP files, drag them onto the site, or paste with Ctrl+V.": "Elige archivos PNG, JPEG o WebP, arrástralos al sitio o pégalos con Ctrl+V.",
  "Select an image in the list to show its preview and settings.": "Selecciona una imagen de la lista para ver su vista previa y sus ajustes.",
  "Delete selected and Delete all only remove images from the list. Your original files are not deleted.": "Eliminar selección y Eliminar todo solo quitan imágenes de la lista. Los archivos originales no se borran.",
  "View the original or adjusted image above and compare the converted result below.": "Mira arriba la imagen original o ajustada y compara abajo el resultado convertido.",
  "Use the mouse wheel to zoom and drag the image to move it.": "Usa la rueda para ampliar y arrastra la imagen para moverla.",
  "Open a palette slot's color swatch and choose Image eyedropper, then click the image to sample the color you want.": "Abre la muestra de una ranura y elige Cuentagotas de imagen; después pulsa la imagen para tomar el color deseado.",
  "Use the lower-right buttons to switch Original/Adjusted, lock the view, or fit the image.": "Usa los botones inferiores derechos para cambiar Original/Ajustado, bloquear la vista o ajustar la imagen.",
  "Adjust the image's brightness, color, and pixel shape before palette conversion.": "Ajusta el brillo, el color y la forma de píxel antes de convertir la paleta.",
  "Brightness lightens or darkens the image. Contrast changes the difference between light and dark areas.": "El brillo aclara u oscurece la imagen. El contraste cambia la diferencia entre zonas claras y oscuras.",
  "Saturation changes color intensity. Hue shifts the overall color family.": "La saturación cambia la intensidad. El tono desplaza la familia cromática general.",
  "Pixelation turns the image into square blocks. Larger blocks create coarser pixels.": "El pixelado convierte la imagen en bloques cuadrados. Los bloques mayores crean píxeles más gruesos.",
  "Smooth alpha keeps partially transparent pixels. Binary alpha makes each pixel fully transparent or fully opaque.": "El alfa suave conserva los píxeles semitransparentes. El alfa binario hace que cada píxel sea totalmente transparente o totalmente opaco.",
  "Choose the color count and palette colors used in the converted result.": "Elige la cantidad de colores y los colores de paleta del resultado.",
  "Enter the final color count to create the same number of palette slots.": "Introduce la cantidad final para crear el mismo número de ranuras.",
  "Click a slot's left color swatch to enter HEX or RGB, or use the Image eyedropper to choose a color.": "Pulsa la muestra izquierda de una ranura para introducir HEX o RGB, o usa el Cuentagotas de imagen.",
  "Auto calculates color and weight. Color fixed keeps only the color. Fixed keeps both color and weight.": "Auto calcula color y peso. Color fijo conserva solo el color. Fijo conserva color y peso.",
  "Raise the weight to make similar pixels more likely to use that palette color.": "Aumenta el peso para que más píxeles similares usen ese color.",
  "Palette tendency changes automatic color selection. Surface cleanup controls how clean the converted color areas look.": "La tendencia cambia la selección automática; la limpieza de superficies controla la claridad de las áreas convertidas.",
  "Keep your settings for later or save converted images as files.": "Conserva los ajustes para más tarde o guarda las imágenes convertidas.",
  "Save color adjustment and palette settings as a JSON file and load them again later.": "Guarda los ajustes de color y paleta como JSON para volver a cargarlos.",
  "Image format": "Formato de imagen",
  "PNG and WebP can preserve transparency. JPEG fills transparent areas with the selected background color.": "PNG y WebP pueden conservar la transparencia. JPEG rellena las zonas transparentes con el fondo elegido.",
  "Keep the original dimensions or save a smaller resolution matched to the pixel blocks.": "Conserva el tamaño original o guarda una resolución menor ajustada a los bloques.",
  "Save only the current image or save every image in the list at once.": "Guarda solo la imagen actual o todas las de la lista a la vez.",
  "Choose one palette for the whole video or generate a new palette for each frame.": "Elige una paleta para todo el vídeo o genera una para cada fotograma.",
  "Analyzes the whole video and keeps the same colors throughout. Recommended for first-time use because it reduces color flicker.": "Analiza todo el vídeo y mantiene los mismos colores. Se recomienda al empezar porque reduce el parpadeo.",
  "Automatically creates colors for each frame. It follows scene changes well, but colors may shift.": "Crea colores para cada fotograma. Sigue bien los cambios de escena, aunque los colores pueden variar.",
  "Apply the same color adjustments and pixelation to every frame.": "Aplica los mismos ajustes de color y pixelado a cada fotograma.",
  "Adjust the video's overall brightness and the difference between light and dark areas.": "Ajusta el brillo general y la diferencia entre zonas claras y oscuras.",
  "Change color intensity and the video's overall color family.": "Cambia la intensidad y la familia cromática general del vídeo.",
  "Pixelation turns the video into square blocks. Larger blocks create coarser pixels.": "El pixelado convierte el vídeo en bloques cuadrados. Los bloques mayores crean píxeles más gruesos.",
  "Choose the color count and palette settings used in the converted video.": "Elige la cantidad de colores y los ajustes de paleta del vídeo convertido.",
  "Presets, fixed colors, and weights apply to every frame.": "Los preajustes, colores fijos y pesos se aplican a cada fotograma.",
  "Colors are generated for every frame, so the fixed colors and weights below are not used.": "Los colores se generan por fotograma, así que no se usan los colores fijos ni los pesos de abajo.",
  "Higher values reduce small color speckles and make broad areas look cleaner.": "Los valores altos reducen pequeñas motas y limpian las áreas amplias.",
  "Changing the final color count updates the number of slots. Press × on a slot to reduce the color count by one.": "Al cambiar la cantidad final también cambia el número de ranuras. Pulsa × en una ranura para reducir un color.",
  "Presets and weights": "Preajustes y pesos",
  "A preset applies its colors as Color fixed with automatic weights. Raising a weight maps more similar pixels to that color.": "Un preajuste aplica sus colores como Color fijo con pesos automáticos. Al aumentar un peso, más píxeles similares usan ese color.",
  "Palette tendency moves between dominant colors, source balance, and color variety. Lower surface cleanup keeps detail; higher values create cleaner broad areas.": "La tendencia de paleta va de colores dominantes a equilibrio original y variedad. Una limpieza baja conserva detalles; una alta crea áreas amplias más limpias.",
  "Choose the color adjustment or palette settings you need, save them as JSON, and load them again later.": "Elige los ajustes de color o paleta que necesites, guárdalos como JSON y vuelve a cargarlos después.",
  "Choose whether to build one palette from the whole video or adjust it automatically for each frame.": "Elige entre crear una paleta para todo el vídeo o ajustarla automáticamente en cada fotograma.",
  "Analyzes representative scenes across the video and uses the same palette throughout. Recommended for first-time use because it reduces color flicker.": "Analiza escenas representativas de todo el vídeo y usa la misma paleta hasta el final. Se recomienda al empezar porque reduce el parpadeo de color.",
  "Builds a palette for each frame and blends it naturally with recent frames. Scene cuts update quickly, but some videos may still show color shifts.": "Crea una paleta para cada fotograma y la enlaza suavemente con los recientes. Los cambios de escena se reflejan rápido, aunque algunos vídeos pueden mostrar variaciones de color.",
  "Fixed colors and weights are ignored, but color count, palette tendency, and surface cleanup still apply.": "No se usan los colores fijos ni los pesos, pero sí la cantidad de colores, la tendencia de paleta y la limpieza de superficies.",
  "The left favors frequently used dominant colors, the center preserves source balance, and the right selects a wider variety of distinct colors.": "La izquierda prioriza los colores dominantes, el centro mantiene el equilibrio original y la derecha elige una mayor variedad de colores distintos.",
  "Lower values keep small color details. Higher values reduce speckles and create cleaner broad areas.": "Los valores bajos conservan pequeños detalles; los altos reducen motas y crean áreas amplias más limpias.",
  "Processing acceleration": "Aceleración de procesamiento",
  "Auto (recommended)": "Automático (recomendado)",
  "Experimental GPU": "GPU experimental",
  "Checking GPU": "Comprobando GPU",
  "GPU unavailable": "GPU no disponible",
  "Browser-selected GPU": "GPU seleccionada por el navegador",
  "GPU is available only for a whole-video common palette with Surface cleanup set to 0.": "La GPU solo está disponible con una paleta común para todo el vídeo y Limpieza de superficies en 0.",
  "Converting with the CPU.": "Convirtiendo con la CPU.",
  "Per-frame automatic palettes are converted with the CPU.": "Las paletas automáticas por fotograma se convierten con la CPU.",
  "Comparing CPU and GPU speed and output.": "Comparando la velocidad y el resultado de CPU y GPU.",
  "GPU output did not match the CPU, so processing automatically switched to the CPU.": "El resultado de la GPU no coincidió con el de la CPU, por lo que se cambió automáticamente a la CPU.",
  "The GPU is unavailable in this browser, so processing automatically switched to the CPU.": "La GPU no está disponible en este navegador, por lo que se cambió automáticamente a la CPU.",
  "The current settings are not eligible for GPU acceleration, so conversion will use the CPU.": "Los ajustes actuales no admiten aceleración por GPU, así que la conversión usará la CPU.",
  "The GPU could not start, so processing automatically switched to the CPU. {reason}": "La GPU no pudo iniciarse, por lo que se cambió automáticamente a la CPU. {reason}",
  "A GPU error occurred, so processing automatically switched to the CPU. {reason}": "Se produjo un error de GPU y se cambió automáticamente a la CPU. {reason}",
  "A GPU error occurred, so processing automatically switched to the CPU. Remaining frames will use the CPU. {reason}": "Se produjo un error de GPU y se cambió automáticamente a la CPU. Los fotogramas restantes usarán la CPU. {reason}",
  "The benchmark favored the CPU, so conversion will use the CPU. GPU: {gpu}": "La prueba favoreció a la CPU, así que la conversión usará la CPU. GPU: {gpu}",
  "Using GPU acceleration: {gpu}": "Usando aceleración por GPU: {gpu}",
  "Unknown error": "Error desconocido",
  "Single-color tint": "Tinte de un solo color",
  "Keeps each pixel's brightness and color intensity while unifying all colors around the selected hue.": "Conserva el brillo y la intensidad de cada píxel mientras unifica todos los colores en torno al tono elegido.",
  "Keeps each frame's brightness and color intensity while unifying it around the selected hue.": "Conserva el brillo y la intensidad de cada fotograma mientras lo unifica en torno al tono elegido.",
  "Unify the hue while preserving brightness and shading": "Unifica el tono conservando el brillo y el sombreado",
  "Enable single-color tint": "Activar tinte de un solo color",
  "Reference color": "Color de referencia",
  "Single-color reference color": "Color de referencia del tinte",
  "Brightness, contrast, saturation, hue, single-color tint, and pixelation": "Brillo, contraste, saturación, tono, tinte de un solo color y pixelado",
  "Reset color adjustments, single-color tint, and pixelation.": "Se restablecieron los ajustes de color, el tinte de un solo color y el pixelado.",
  "The single-color tint setting is invalid.": "El ajuste de tinte de un solo color no es válido.",
  "The single-color reference color is invalid.": "El color de referencia del tinte no es válido.",
  "Unify the main hue · Shift it with Hue": "Unifica el tono principal · Cámbialo con Tono",
  "Keeps pixel brightness and color intensity, unifies the image around its most-used hue, and shifts that hue with the Hue control.": "Conserva el brillo y la intensidad, unifica la imagen en torno a su tono más usado y lo desplaza con el control Tono.",
  "Keeps frame brightness and color intensity, unifies it around the main hue, and shifts that hue with the Hue control.": "Conserva el brillo y la intensidad del fotograma, lo unifica en torno al tono principal y lo desplaza con el control Tono.",
};
